#!/usr/bin/env bash

info() {
	echo "[INFO]" $@
}

fatal() {
	echo "[FATAL]" $@
	exit 1
}

invalid_machines() {
	info "invalid machines"
	find machines/ko -type f | xargs -i{} -t cabal run ft-turing -- {} "1-1="
}

_p() {
	echo "${1}" | tr -d "\t" | head -n 1 | cut -f 2 -d "\""
	echo "${1}" | tr -d "\t" | grep "Current" | cut -f 4 -d ' '
	echo "${1}" | tail -n 2
}

inception() {
	for i in $(cabal run Inception-tape); do
		cabal run ft-turing -- machines/inception.json "$i" | tail -n 2
	done
}

functioning_machines() {
	info "functioning machines"
	_p "$(cabal run ft-turing -- machines/unary_sub.json "111-11=")"
	_p "$(cabal run ft-turing -- machines/unary_add.json "111+11")"
	_p "$(cabal run ft-turing -- machines/palindrome.json "111000")"
	_p "$(cabal run ft-turing -- machines/palindrome.json "101101")"
	_p "$(cabal run ft-turing -- machines/0n1n.json "0011")"
	_p "$(cabal run ft-turing -- machines/0n1n.json "00111")"
	_p "$(cabal run ft-turing -- machines/o2n.json "00")"
	_p "$(cabal run ft-turing -- machines/o2n.json "000")"
	echo "inception: unary addition"
	inception
}

main() {
	cabal build 2>&1 >/dev/null || fatal "could not build project" && info "built successfully"
	[[ -z "$@" || "$1" = "ko" ]] && invalid_machines
	[[ -z "$@" || "$1" = "ok" ]] && functioning_machines
}

main $@
